name: Docker
on: 
  push:
    branches: [ master ]
  pull_request:
     branches: [ master ]
     
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_email: "godsonaddy@yahoo.co.uk"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "weatherappwrld"
          remote_branch: "main"
          healthcheck: "https://weatherappwrld.herokuapp.com"
